app:
  name: "GoBlast"
  environment: "development"
  port: 8080
  jwt_secret: "GoBlast"

database:
  host: db
  port: 5432
  user: postgres
  password: 3215
  name: goblast
  sslmode: disable # Или другой режим, если требуется


broker:
  url: nats://goblast_nats:4222


encrypted:
  encryption_key: "12345678901234567890123456789012"