app:
  name: "GoBlast"
  environment: "development"
  port: 8080
  jwt_secret: "GoBlast"

database:
  host: localhost    #localhost or db
  port: 5432
  user: postgres
  password: 3215
  name: goblast
  sslmode: disable # Или другой режим, если требуется


broker:
  url: nats://localhost:4222 #goblast_nats or localhost

encrypted:
  encryption_key: "12345678901234567890123456789012"